{% set name = "swmm-toolkit" %}
{% set version = "0.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
    sha256: ae213a1b4a0a3c841061bdaf20d74ee37dd45de83eded2d5314362b488066568
  - git_url: https://github.com/pyswmm/Stormwater-Management-Model
    git_rev: 24cdf73c3d7cf3bb62f0bff150d5987f1f826889
    folder: swmm-solver

build:
  script:
    - set NO_STABLE_ABI=true  # [win]
    - export NO_STABLE_ABI=true  # [unix]
    - export SKBUILD_CMAKE_ARGS="-GUnix Makefiles"  # [unix]
    - export SKBUILD_CMAKE_ARGS="-GUnix Ninja"  # [win]
    - export CFLAGS="${CFLAGS} -D_FORTIFY_SOURCE=2"  # [osx]
    - export CXXFLAGS="${CXXFLAGS} -D_FORTIFY_SOURCE=2"  # [osx]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

  number: 0
  skip: true  # [py<38]
  missing_dso_whitelist:   # [win]
    - "*/swmm5.dll"  # [win]
    - "*/swmm-output.dll"  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cmake >=3.21
    - swig >=4.4.0
    - make  # [unix]
    - ninja  # [win]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - setuptools >=42
    - scikit-build-core >=0.4.3
    - pip
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  run:
    - python
    - aenum >=3.1.11

test:
  imports:
    - swmm.toolkit.solver
    - swmm.toolkit.output
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OpenWaterAnalytics/swmm-python
  summary: OWA SWMM Python Toolkit
  license: CC0-1.0
  license_file:
    - LICENSE.md
    - swmm-solver/LICENSE

extra:
  recipe-maintainers:
    - karosc
    - cheginit
